[project]
name = "graphfusionvuldetect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "slither-analyzer>=0.10.0",
    "anyio>=4.11.0",
    "datasets>=4.0.0",
    "dgl>=1.1,<2.0",
    "fastapi>=0.121.2",
    "langchain-core>=1.0.5",
    "langchain-openai>=1.0.3",
    "langgraph>=1.0.3",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "py-solc==3.2.0",
    "python-multipart>=0.0.20",
    "rootutils>=1.0.7",
    "scikit-learn>=1.7.1",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "transformers>=4.55.2",
    "typer>=0.16.0",
    "uvicorn>=0.38.0",
]
