[project]
name = "graphfusionvuldetect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.0.0",
    "dgl==2.0.0",
    "langchain-core>=1.0.5",
    "langgraph>=1.0.3",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "py-solc==3.2.0",
    "rootutils>=1.0.7",
    "scikit-learn>=1.7.1",
    "slither-analyzer==0.8.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "transformers>=4.55.2",
    "typer>=0.16.0",
]
